### ISSUE TITLE
Dynamically define methods that return DOM elements

### ISSUE THREAD

**Issue by crismali** [daytonn/jskit#8]
Just spitballing a bit here, but it would be great if you could write:

```js
App.createController("Foos", {
  actions: ["new"],

  elements: {
    expandModalButton: ".foo .open-modal",
    modal: ".modal"
  },

  new: function(stripeKey) {
    this.registerEvents();
    // ...
  },

  registerEvents: function() {
    this.$expandModalButton().on("click", this.expandModal);
  },
  
  expandModal: function() {
    this.$modal().removeClass("hidden");
  }
});
```

This is a bit of a different pattern than what I proposed in #7. Instead of defining a `cacheElements` method it defines a method for each named element. 

The `$element` methods would be defined as something like this:

```js
function defineElementMethods(controller) {
  _.each(controller.elements, function(name, selector) {
    controller["$" + name] = function() { return $(selector); };
  });
}
```

What I like about this is never needing to remember to call some sort of `cacheElements` method in my code or tests.

Also, if JSkit defined `cacheElements` for me, I'd sort of just want it call that for me anyway when the action is triggered (and I'd need away to call it myself and kill the cache if I ever sideloaded content).

**Comment by daytonn** [comment]
I like this idea, the methods would need to memoize the selected element or else we're really just talking about using `this.$foo = $("#foo");`.
